### ISSUE TITLE
Debug method lireDictionnaire de class FichierUtilitaire

### ISSUE THREAD

**Issue by WildSource** [ShadyFox2004/TP5#1]
Le test pour une raison ne marche pas sa fait un no such element exception, Quand je le faisais avant sa marchait mais il y a tellement de mot je ne suis pas sur que la methode lit tous les mots. Il ne faut pas oublier d'ajouter le fichier texte du dictionnaire

**Comment by Henri-ba** [comment]
je vais debug lireDictionaire
